std_msgs/Header header

float64 gps_time
int32 week

uint32 location_mode
float64 variance
string status

float64 latitude
float64 longitude
float64 altitude

float64 lateral_speed
float64 longitudinal_speed
float64 vertical_speed

float64 lateral_accelerate
float64 longitudinal_accelerate
float64 vertical_accelerate

float64 roll
float64 pitch
float64 yaw

float64 roll_rate
float64 pitch_rate
float64 yaw_rate

int32 flag
int32 n

